In [1]:
import pandas as pd

intakes = pd.read_csv("aac_intakes.csv")
outcomes = pd.read_csv("aac_outcomes.csv")

In [7]:
intakes.head()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,Belle,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,Runster,Intact Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,NaN,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,Rio,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,Odin,Neutered Male

In [3]:
outcomes.head()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown

In [6]:
df = pd.merge(intakes, outcomes, on="animal_id", how="inner")
df

,age_upon_intake,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime2,found_location,intake_condition,intake_type,...,animal_type_y,breed_y,color_y,date_of_birth,datetime_y,monthyear,name_y,outcome_subtype,outcome_type,sex_upon_outcome
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,...,Dog,English Springer Spaniel,White/Liver,2007-07-05T00:00:00,2015-07-05T15:13:00,2015-07-05T15:13:00,Belle,NaN,Return to Owner,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,...,Dog,Basenji Mix,Sable/White,2015-04-17T00:00:00,2016-04-21T17:17:00,2016-04-21T17:17:00,Runster,NaN,Return to Owner,Neutered Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,...,Cat,Domestic Shorthair Mix,Calico,2013-09-21T00:00:00,2013-10-21T11:39:00,2013-10-21T11:39:00,NaN,Partner,Transfer,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,...,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2010-06-29T00:00:00,2014-07-02T14:16:00,2014-07-02T14:16:00,Rio,NaN,Return to Owner,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,...,Dog,Labrador Retriever Mix,Chocolate,2015-02-18T00:00:00,2017-02-21T17:44:00,2017-02-21T17:44:00,Odin,NaN,Return to Owner,Neutered Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100225,5 years,A768934,Dog,Dachshund Wirehair/Chihuahua Shorthair,Chocolate/White,2018-03-27T14:27:00.000,2018-03-27T14:27:00.000,603 West Johanna Street in Austin (TX),Normal,Stray,...,Dog,Dachshund Wirehair/Chihuahua Shorthair,Chocolate/White,2013-03-27T00:00:00,2018-04-02T13:01:00,2018-04-02T13:01:00,*Billy,Partner,Transfer,Neutered Male
100226,2 years,A769064,Other,Bat Mix,Brown,2018-03-29T17:13:00.000,2018-03-29T17:13:00.000,2519 Scarbrough Dr in Travis (TX),Normal,Wildlife,...,Other,Bat Mix,Brown,2016-03-29T00:00:00,2018-03-29T18:30:00,2018-03-29T18:30:00,NaN,Rabies Risk,Euthanasia,Unknown
100227,3 years,A675680,Dog,German Shepherd/Black/Tan Hound,Black/Brown,2014-03-31T18:10:00.000,2014-03-31T18:10:00.000,Austin (TX),Normal,Public Assist,...,Dog,German Shepherd/Black/Tan Hound,Black/Brown,2011-03-31T00:00:00,2014-04-09T13:16:00,2014-04-09T13:16:00,Draco,NaN,Return to Owner,Neutered Male
100228,1 year,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2014-06-10T11:53:00.000,4605 Lyra Cir in Austin (TX),Normal,Stray,...,Dog,Chihuahua Shorthair/Beagle,Tan,2013-06-10T00:00:00,2014-06-14T18:07:00,2014-06-14T18:07:00,Lolo,NaN,Adoption,Neutered Male
100229,1 year,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2014-06-10T11:53:00.000,4605 Lyra Cir in Austin (TX),Normal,Stray,...,Dog,Chihuahua Shorthair/Beagle,Tan,2013-06-10T00:00:00,2018-03-22T13:29:00,2018-03-22T13:29:00,Lolo,NaN,Return to Owner,Neutered Male

In [8]:
df.head()

,age_upon_intake,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime2,found_location,intake_condition,intake_type,...,animal_type_y,breed_y,color_y,date_of_birth,datetime_y,monthyear,name_y,outcome_subtype,outcome_type,sex_upon_outcome
0,8 years,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T12:59:00.000,9409 Bluegrass Dr in Austin (TX),Normal,Stray,...,Dog,English Springer Spaniel,White/Liver,2007-07-05T00:00:00,2015-07-05T15:13:00,2015-07-05T15:13:00,Belle,NaN,Return to Owner,Spayed Female
1,11 months,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-14T18:43:00.000,2818 Palomino Trail in Austin (TX),Normal,Stray,...,Dog,Basenji Mix,Sable/White,2015-04-17T00:00:00,2016-04-21T17:17:00,2016-04-21T17:17:00,Runster,NaN,Return to Owner,Neutered Male
2,4 weeks,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T07:59:00.000,Austin (TX),Sick,Stray,...,Cat,Domestic Shorthair Mix,Calico,2013-09-21T00:00:00,2013-10-21T11:39:00,2013-10-21T11:39:00,NaN,Partner,Transfer,Intact Female
3,4 years,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-06-29T10:38:00.000,800 Grove Blvd in Austin (TX),Normal,Stray,...,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2010-06-29T00:00:00,2014-07-02T14:16:00,2014-07-02T14:16:00,Rio,NaN,Return to Owner,Neutered Male
4,2 years,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-18T12:46:00.000,Austin (TX),Normal,Owner Surrender,...,Dog,Labrador Retriever Mix,Chocolate,2015-02-18T00:00:00,2017-02-21T17:44:00,2017-02-21T17:44:00,Odin,NaN,Return to Owner,Neutered Male

In [9]:
df.shape

(100230, 23)

In [11]:
df = df[[
    'animal_id',
    'animal_type_x',
    'breed_x',
    'color_x',
    'datetime_x',
    'datetime_y',
    'outcome_type',
    'sex_upon_intake',
    'age_upon_intake'
]]
df

,animal_id,animal_type_x,breed_x,color_x,datetime_x,datetime_y,outcome_type,sex_upon_intake,age_upon_intake
0,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T15:13:00,Return to Owner,Spayed Female,8 years
1,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-21T17:17:00,Return to Owner,Intact Male,11 months
2,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T11:39:00,Transfer,Intact Female,4 weeks
3,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-07-02T14:16:00,Return to Owner,Neutered Male,4 years
4,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-21T17:44:00,Return to Owner,Neutered Male,2 years
...,...,...,...,...,...,...,...,...,...
100225,A768934,Dog,Dachshund Wirehair/Chihuahua Shorthair,Chocolate/White,2018-03-27T14:27:00.000,2018-04-02T13:01:00,Transfer,Intact Male,5 years
100226,A769064,Other,Bat Mix,Brown,2018-03-29T17:13:00.000,2018-03-29T18:30:00,Euthanasia,Unknown,2 years
100227,A675680,Dog,German Shepherd/Black/Tan Hound,Black/Brown,2014-03-31T18:10:00.000,2014-04-09T13:16:00,Return to Owner,Neutered Male,3 years
100228,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2014-06-14T18:07:00,Adoption,Intact Male,1 year
100229,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2018-03-22T13:29:00,Return to Owner,Intact Male,1 year

In [12]:
df = df.rename(columns={
    'animal_id': 'AnimalID',
    'animal_type_x': 'AnimalType',
    'breed_x': 'Breed',
    'color_x': 'Color',
    'datetime_x': 'EntryDate',
    'datetime_y': 'ReleaseDate',
    'outcome_type': 'OutcomeType',
    'sex_upon_intake': 'Sex',
    'age_upon_intake': 'Age'
})

In [13]:
df

,AnimalID,AnimalType,Breed,Color,EntryDate,ReleaseDate,OutcomeType,Sex,Age
0,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05T12:59:00.000,2015-07-05T15:13:00,Return to Owner,Spayed Female,8 years
1,A724273,Dog,Basenji Mix,Sable/White,2016-04-14T18:43:00.000,2016-04-21T17:17:00,Return to Owner,Intact Male,11 months
2,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21T07:59:00.000,2013-10-21T11:39:00,Transfer,Intact Female,4 weeks
3,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29T10:38:00.000,2014-07-02T14:16:00,Return to Owner,Neutered Male,4 years
4,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18T12:46:00.000,2017-02-21T17:44:00,Return to Owner,Neutered Male,2 years
...,...,...,...,...,...,...,...,...,...
100225,A768934,Dog,Dachshund Wirehair/Chihuahua Shorthair,Chocolate/White,2018-03-27T14:27:00.000,2018-04-02T13:01:00,Transfer,Intact Male,5 years
100226,A769064,Other,Bat Mix,Brown,2018-03-29T17:13:00.000,2018-03-29T18:30:00,Euthanasia,Unknown,2 years
100227,A675680,Dog,German Shepherd/Black/Tan Hound,Black/Brown,2014-03-31T18:10:00.000,2014-04-09T13:16:00,Return to Owner,Neutered Male,3 years
100228,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2014-06-14T18:07:00,Adoption,Intact Male,1 year
100229,A680949,Dog,Chihuahua Shorthair/Beagle,Tan,2014-06-10T11:53:00.000,2018-03-22T13:29:00,Return to Owner,Intact Male,1 year

In [14]:
df['EntryDate'] = pd.to_datetime(df['EntryDate'])
df['ReleaseDate'] = pd.to_datetime(df['ReleaseDate'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100230 entries, 0 to 100229
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   AnimalID     100230 non-null  object
 1   AnimalType   100230 non-null  object
 2   Breed        100230 non-null  object
 3   Color        100230 non-null  object
 4   EntryDate    100230 non-null  datetime64[ns]
 5   ReleaseDate  100230 non-null  datetime64[ns]
 6   OutcomeType  100214 non-null  object
 7   Sex          100229 non-null  object
 8   Age          100230 non-null  object
dtypes: datetime64[ns](2), object(7)
memory usage: 6.9+ MB

In [16]:
df['Year'] = df['ReleaseDate'].dt.year
df['Month'] = df['ReleaseDate'].dt.month

In [17]:
df.head()

,AnimalID,AnimalType,Breed,Color,EntryDate,ReleaseDate,OutcomeType,Sex,Age,Year,Month
0,A706918,Dog,English Springer Spaniel,White/Liver,2015-07-05 12:59:00,2015-07-05 15:13:00,Return to Owner,Spayed Female,8 years,2015,7
1,A724273,Dog,Basenji Mix,Sable/White,2016-04-14 18:43:00,2016-04-21 17:17:00,Return to Owner,Intact Male,11 months,2016,4
2,A665644,Cat,Domestic Shorthair Mix,Calico,2013-10-21 07:59:00,2013-10-21 11:39:00,Transfer,Intact Female,4 weeks,2013,10
3,A682524,Dog,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,2014-06-29 10:38:00,2014-07-02 14:16:00,Return to Owner,Neutered Male,4 years,2014,7
4,A743852,Dog,Labrador Retriever Mix,Chocolate,2017-02-18 12:46:00,2017-02-21 17:44:00,Return to Owner,Neutered Male,2 years,2017,2

In [18]:
df['IsAdopted'] = df['OutcomeType'] == 'Adoption'

In [19]:
df[['OutcomeType', 'IsAdopted']].head(10)

       OutcomeType  IsAdopted
0  Return to Owner      False
1  Return to Owner      False
2         Transfer      False
3  Return to Owner      False
4  Return to Owner      False
5  Return to Owner      False
6         Transfer      False
7         Adoption       True
8         Adoption       True
9         Adoption       True

In [20]:
df.isnull().sum()

AnimalID        0
AnimalType      0
Breed           0
Color           0
EntryDate       0
ReleaseDate     0
OutcomeType    16
Sex             1
Age             0
Year            0
Month           0
IsAdopted       0
dtype: int64

In [21]:
df = df.dropna(subset=['AnimalType', 'OutcomeType', 'ReleaseDate'])

In [26]:
df.duplicated().sum()

0

In [23]:
df = df.drop_duplicates()

In [27]:
df.to_csv("final_data.csv", index=False)

In [28]:
df.to_csv("final_data.csv", index=False)